name: Envio telegram cada hora solo pm

#on:
#  schedule:
#    - cron: '0 08-10 * * *'  # Ejecutar cada hora entre 10:00 AM y 12:00 PM
#  push:
#    branches: 
#      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
  
    env:
      TOKEN: ${{ secrets.TOKEN }}
      ID: ${{ secrets.ID }}    

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py